spring:
  dataSource: #Настраиваем подключение к БД
    url: jdbc:h2:file:./testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  quartz:
    job-store-type: jdbc #Указываем, что будем хранить информацию о джобах в БД, а не в памяти
    jdbc:
      initialize-schema: never #Мы будем инициализировать схему БД вручную, поэтому ставим never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #Используев AUTO, для того, чтобы каждый новый инстанс Scheduler`a имел уникальное название.
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #Указываем диалект для запросов к БД
            useProperties: false #Указываем, что все данные в БД будут храниться в качестве строк, а не в двоичном формате
            tablePrefix: QRTZ_  #Префикс таблиц в БД
            clusterCheckinInterval: 5000 #Указываем частоту сверки инстанса Scheduler с остальными инстансами в кластере
            isClustered: true #Включаем режим работы в кластере
          threadPool: #Указываем настройки для создания пула поток, на котором будут выполняться джобы
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
    auto-startup: false #Выключаем автоматический старт для scheduler, т.к. запуск будет выполнен вручную

scheduler:
  permanent-jobs-group-name: PERMANENT
  show-time-job-cron: ${SHOW_TIME_JOB_CRON:0 0 * * * ?}